### ISSUE TITLE
更改组件数据，组件没有更新

### ISSUE THREAD

**Issue by neil-i** [215566435/Dragact#6]
在更新组件展示数据后，执行 setstate(),组件的展示数据还是旧数据(非坐标信息)，没有更新

**Comment by 215566435** [comment]
@neil-i 明白bug在哪里了。今晚修

**Comment by 215566435** [comment]
@neil-i 

更新你的dragact，到达最新版本
修改package.json中的
```json
dragact:0.2.7
```


```
npm update dragact
```

**Comment by neil-i** [comment]
现在已经更新到0.2.7了，但是我查看源码，发现您改动的代码没有下载到我的工程里，这个是什么原因，我还需要做别的操作么？
3q！！！

**Comment by 215566435** [comment]
噢。。。我忘记推送了。稍等

**Comment by 215566435** [comment]
已经推送

**Comment by neil-i** [comment]
可以了，非常感谢！
